image: rocker/r-devel:latest

before_script:
  - apt-get install -y --no-install-recommends libcurl4-openssl-dev libssh2-1-dev libssl-dev libxml2-dev libgeos-dev git
  - apt install -y r-cran-devtools
  - R --vanilla -e 'chooseCRANmirror(graphics = F, ind = 1); install.packages(c("roxygen2", "sp", "RcppArmadillo", "rgeos", "knitr", "rmarkdown"))'

document:
  stage: document
  script:
  - R --vanilla -e 'devtools::document();'
  artifacts:
    paths:
    - man/
    - NAMESPACE

build:
  stage: build
  script:
  - R --vanilla -e 'devtools::build(path = "./")'
  artifacts:
    paths:
    - '*.tar.gz'
  dependencies:
  - document

check:
  stage: check
  script:
  - R --vanilla -e 'tar_file <- file.path(getwd(), list.files(".",
    pattern = ".tar.gz")); results <- devtools::check_built(tar_file); stopifnot(sum(sapply(results,
    length)) <= 0)'
  dependencies:
  - build

stages:
- document
- build
- check

